name: Create release package
on:
  workflow_dispatch:
    inputs:
      PACKAGE_VERSION:
        description: 'Package Version'
        required: true
jobs:
  create_archive:
    uses: inpsyde/reusable-workflows/.github/workflows/build-plugin-archive.yml@main
    secrets:
      COMPOSER_AUTH_JSON: ${{ secrets.PACKAGIST_AUTH_JSON }}
    with:
      PLUGIN_MAIN_FILE: ./mollie-payments-for-woocommerce.php
      PLUGIN_VERSION: ${{ inputs.PACKAGE_VERSION }}
      ARCHIVE_NAME: mollie-payments-for-woocommerce
